
logging:
  level:
    com.dawu: trace
    org.springframework: warn
  config: classpath:logback.xml

--- # Spring Boot Admin Client 客户端的相关配置
spring:
  boot:
    admin:
      client:
        # 增加客户端开关
        enabled: true
        # 设置 Spring Boot Admin Server 地址
        url: http://localhost:9090/admin
        instance:
          prefer-ip: true # 注册实例时，优先使用 IP
        username: ruoyi
        password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api
  # 标题
  title: '语音产品_接口文档'
  # 描述
  description: '用于产品接口信息'
  # 版本
  version: '1.0.0'
  # 是否开启增强
knife4j:
  enable: true
