# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /

spring:
  profiles:
    active: dev
    include:
      - config-default
      - config-mybatis
      - config-redisson

# 项目相关配置
project:
  # 名称
  name: tochat
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 上传地址
  profile: /opt/project/ItcEye/uploadPath
  # 包地址
  package: com.dawu.tochat
