
logging:
  level:
    com.dawu: trace
    org.springframework: warn
  config: classpath:logback.xml

--- # Spring Boot Admin Client 客户端的相关配置
spring:
  boot:
    admin:
      client:
        # 增加客户端开关
        enabled: true
        # 设置 Spring Boot Admin Server 地址
        url: http://localhost:9090/admin
        instance:
          prefer-ip: true # 注册实例时，优先使用 IP
        username: ruoyi
        password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
