spring:
  datasource:
    url: jdbc:mysql://49.232.11.111:3306/chat?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: w18611805440
    driver-class-name: com.mysql.cj.jdbc.Driver

