spring:
  datasource:
    url: jdbc:mysql://49.232.11.111:3306/chat?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: w18611805440
    driver-class-name: com.mysql.cj.jdbc.Driver

--- # redis 配置
spring:
  redis:
    # 地址
    host: 49.232.11.111
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false
